'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class main

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbl_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nama As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tlp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tlp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmb_source_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_source_type As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_source_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_source_type As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_group_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_group_type As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_group_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_group_type As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_transaction_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_transaction_type As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_transaction_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_transaction_type As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_brand As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_brand As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_product As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_product As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_problem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_problem As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_problem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_problem As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_priority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_priority As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_priority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_priority As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_severity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_severity As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_severity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_severity As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_status As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_status As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl_agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_agent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_nik_agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nik_agent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_date_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_date_create As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_interaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_interaction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltr_interaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltr_interaction As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txt_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_sla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_sla As Global.System.Web.UI.WebControls.Label
End Class
